### ISSUE TITLE
MissingPluginException(No implementation found for method initialize...

### ISSUE THREAD

**Issue by estevez-dev** [vrtdev/flutter_workmanager#63] opened 2019-09-10 14:15 UTC
I'm using `workmanager: ^0.1.0`

Getting an error calling `initialize` method:
```
MissingPluginException(No implementation found for method initialize on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
```
My `main.dart`:
```dart
import 'package:workmanager/workmanager.dart' as workManager;

...

void main() async {
  FlutterError.onError = (errorDetails) {
    Logger.e( "${errorDetails.exception}");
    if (Logger.isInDebugMode) {
      FlutterError.dumpErrorToConsole(errorDetails);
    }
  };

  runZoned(() {
    workManager.Workmanager.initialize(
        LocationManager.updateDeviceLocationIsolate,
        isInDebugMode: Logger.isInDebugMode
    );
    runApp(new HAClientApp());

  }, onError: (error, stack) {
    Logger.e("$error");
    Logger.e("$stack");
    if (Logger.isInDebugMode) {
      debugPrint("$stack");
    }
  });
}

...

```

My `Application.java`:
```java
package com.keyboardcrumbs.hassclient;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import be.tramckrijte.workmanager.WorkmanagerPlugin;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        WorkmanagerPlugin.setPluginRegistrantCallback(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```

Part of my `AndroidManifest.xml`:
```xml
....

<application
        android:name=".Application"
        android:label="HA Client"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">

...

```

**Comment by estevez-dev** [comment] 2019-09-10 14:25
More stranger things happens. I'm still getting notifications about tasks execution )) But the error with `MissingPluginException` present on app start.
![Screenshot_20190910-172253](https://user-images.githubusercontent.com/1819786/64622445-08842300-d3f0-11e9-8d3b-7b16f965a0a0.png)

**Comment by timrijckaert** [comment] 2019-09-11 06:13
I tried to modify the sample application to your sample.
However I'm unable to reproduce the error.

I see that you have the application publically available. 
Do you have a branch I can try?

**Comment by estevez-dev** [comment] 2019-09-11 09:06
Sure. It is in [location_manager_on_worker](https://github.com/estevez-dev/ha_client/tree/features/location_manager_on_worker) branch.
Also I want to say THANK YOU for the grate implementation. I'm tasting it during two days and it works just like it should even if application was terminated by OS. Grate plug in.
This issue actually not critical, because it still works. #64 is a blocker actually.

**Comment by timrijckaert** [comment] 2019-09-14 07:03
Unable to reproduce. Closing for now.

**Closed by timrijckaert** 2019-09-14 07:03 UTC
Labels: android, bug

**Comment by jamesncl** [comment] 2020-07-30 16:50
FWIW, I've also encounter this error, but only on one iOS device in the wild - I'm unable to reproduce in my development environment
